Repository treejh/booktree, pull requests merged in 2025-04, with the labels that each got.

#54 Refact/#44 댓글기능수정
  backend/.gitignore
  backend/build.gradle.kts
  backend/db_dev.trace.db
  backend/gradlew
  backend/src/main/java/com/example/booktree/comment/controller/CommentController.java
  backend/src/main/java/com/example/booktree/comment/dto/CommentDto.java
  backend/src/main/java/com/example/booktree/comment/entity/Comment.java
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/reply/controller/ReplyController.java
  backend/src/main/java/com/example/booktree/user/repository/UserRepository.java
  backend/src/main/resources/application.yml
Labels: refact

#58 [ feat ] #18 : 이미지 파일 업로드 기능 추가와 순환 참조 이슈 해결
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/request/PostRequestDto.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: bug, feature

#59 [ feat] : #49 feat 회원 정보 조회/수정/삭제
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/user/controller/UserController.java
  backend/src/main/java/com/example/booktree/user/dto/request/UserPasswordRequestDto.java
  backend/src/main/java/com/example/booktree/user/dto/request/UserPatchRequestDto.java
  backend/src/main/java/com/example/booktree/user/dto/request/UserPhoneNumberRequestDto.java
  backend/src/main/java/com/example/booktree/user/dto/response/UserProfileResponseDto.java
  backend/src/main/java/com/example/booktree/user/service/TokenService.java
  backend/src/main/java/com/example/booktree/user/service/UserService.java
Labels: feature

#62 [ feat ] : 비밀번호, 핸드폰 번호로 아이디 찾기, 이메일, 핸드폰번호로 비밀번호 찾기
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/user/controller/UserController.java
  backend/src/main/java/com/example/booktree/user/dto/request/UserPasswordRequestDto.java
  backend/src/main/java/com/example/booktree/user/repository/UserRepository.java
  backend/src/main/java/com/example/booktree/user/service/UserService.java
  backend/src/main/java/com/example/booktree/utils/CreateRandomNumber.java
  backend/src/main/java/com/example/booktree/utils/dto/ApiResponseDto.java
Labels: feature

#63 [Refact] #53 : 대댓글기능수정
  backend/src/main/java/com/example/booktree/reply/controller/ReplyController.java
  backend/src/main/java/com/example/booktree/reply/dto/ReplyDto.java
  backend/src/main/java/com/example/booktree/reply/entity/Reply.java
  backend/src/main/java/com/example/booktree/reply/service/ReplyService.java
Labels: refact

#70 #64 댓글페이징처리
  backend/src/main/java/com/example/booktree/comment/controller/CommentController.java
  backend/src/main/java/com/example/booktree/comment/dto/CommentDto.java
  backend/src/main/java/com/example/booktree/comment/repository/CommentRepository.java
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/reply/controller/ReplyController.java
  backend/src/main/java/com/example/booktree/reply/repository/ReplyRepository.java
  backend/src/main/java/com/example/booktree/reply/service/ReplyService.java
  backend/src/main/java/com/example/booktree/user/repository/UserRepository.java
Labels: feature

#74 Feat/#40 게시글좋아요
  backend/src/main/java/com/example/booktree/LikePost/controller/LikePostController.java
  backend/src/main/java/com/example/booktree/LikePost/dto/LikeUserListDto.java
  backend/src/main/java/com/example/booktree/LikePost/dto/request/LikePostRequestDto.java
  backend/src/main/java/com/example/booktree/LikePost/dto/response/LikePostResponseDto.java
  backend/src/main/java/com/example/booktree/LikePost/entity/LikePost.java
  backend/src/main/java/com/example/booktree/LikePost/repository/LikePostRepository.java
  backend/src/main/java/com/example/booktree/LikePost/service/LikePostService.java
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/post/entity/Post.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  backend/src/main/java/com/example/booktree/reply/service/ReplyService.java
  backend/src/main/java/com/example/booktree/user/repository/UserRepository.java
  backend/src/main/resources/application.yml
Labels: feature, refact

#79 [ feat] #60 oauth 깃허브 로그인 구현
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/example/booktree/oauth/resolver/CustomAuthorizationRequestResolver.java
  backend/src/main/java/com/example/booktree/oauth/service/CustomOAuth2UserService.java
  backend/src/main/java/com/example/booktree/user/entity/User.java
  backend/src/main/java/com/example/booktree/user/repository/UserRepository.java
  backend/src/main/java/com/example/booktree/user/service/TokenService.java
  backend/src/main/java/com/example/booktree/user/service/UserService.java
  backend/src/main/resources/application.yml
  frontend/src/app/page.tsx
Labels: feature

#78 [ feat ] #77 : 게시글 Id, 유저 Id, 블로그 Id 별로 게시글 조회
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: feature

#83 [ fix ] : #82 팔로잉 페이지 get builder 오류 해결
  backend/src/main/java/com/example/booktree/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/response/PostFollowingPageDto.java
Labels: bug

#87 [ feat ] : #86 refact 유저 기능 수정
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/user/controller/UserController.java
  backend/src/main/java/com/example/booktree/user/dto/request/UserPasswordRequestDto.java
  backend/src/main/java/com/example/booktree/user/dto/response/UserMyPageResponseDto.java
  backend/src/main/java/com/example/booktree/user/dto/response/UserProfileResponseDto.java
  backend/src/main/java/com/example/booktree/user/service/UserService.java
  frontend/src/app/layout.tsx
Labels: refact

#85 [ feat ] #69 : 실시간 인기 게시글
  backend/build.gradle.kts
  backend/src/main/java/com/example/booktree/category/service/CategoryService.java
  backend/src/main/java/com/example/booktree/config/RedisConfig.java
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/popularpost/controller/PopularPostController.java
  backend/src/main/java/com/example/booktree/popularpost/service/PopularPostService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/response/PostFollowingPageDto.java
  backend/src/main/java/com/example/booktree/post/entity/Post.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  backend/src/test/java/com/example/booktree/popularpost/service/PopularPostServiceTest.java
Labels: feature

#80 [ feat ] #72 : 검색기능추가
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: feature

#84 [ feat ] #81 : 게시글 클릭 시에 반환하게 될 게시글의 세부정보 dto 추가와 적용
  backend/src/main/java/com/example/booktree/LikePost/controller/LikePostController.java
  backend/src/main/java/com/example/booktree/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/response/PostDetailResponseDto.java
  backend/src/main/java/com/example/booktree/post/dto/response/PostFollowingPageDto.java
Labels: refact

#91 Feat/#75블로그 게시글 페이징
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/response/PostFollowingPageDto.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: feature

#94 [ feat ] : #93 팔로잉한 글 불러오기 컨트롤러 메서드 추가
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
Labels: feature

#92 [ refact ] : #90 블로그 기능 수정
  backend/src/main/java/com/example/booktree/blog/controller/BlogController.java
  backend/src/main/java/com/example/booktree/blog/dto/response/BlogResponseDto.java
  backend/src/main/java/com/example/booktree/blog/service/BlogService.java
Labels: refact

#96 [ front ] #88 : 블로그 메인 페이지 임시작성
  frontend/src/app/globals.css
  frontend/src/app/page.tsx
Labels: front

#102 [ feat ] : #98 사용자가 좋아요 누른 게시글 불러오기
  backend/src/main/java/com/example/booktree/LikePost/repository/LikePostRepository.java
  backend/src/main/java/com/example/booktree/LikePost/service/LikePostService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: feature

#104 [ refact ] : #103 사용자가 팔로잉한 유저 글 불러오기 페이징 처리 수정
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: refact

#109 Front/#101 계정
  frontend/src/app/example/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/login.module.css
  frontend/src/app/login/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/app/register/register.module.css
  frontend/src/app/withdrawal/page.tsx
  frontend/src/app/withdrawal/withdrawal.module.css
Labels: front

#105 [ feat ] : #99 api 접근 권한 설정하기 config
  backend/src/main/java/com/example/booktree/category/controller/CategoryController.java
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/image/controller/ImageController.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
Labels: feature

#110 [ feat ] : #106 blog,follow page
  frontend/src/app/blog/page.tsx
  frontend/src/app/follow/page.tsx
Labels: front

#120 [ front ] #111 : 계정 관련 페이지들
  frontend/src/app/account/findAccount/findId/findId.module.css
  frontend/src/app/account/findAccount/findId/page.tsx
  frontend/src/app/account/findAccount/findPassword/findPassword.module.css
  frontend/src/app/account/findAccount/findPassword/page.tsx
  frontend/src/app/account/login/login.module.css
  frontend/src/app/account/login/page.tsx
  frontend/src/app/account/signup/page.tsx
  frontend/src/app/account/signup/signup.module.css
  frontend/src/app/account/withdraw/page.tsx
  frontend/src/app/account/withdraw/withdraw.module.css
Labels: front

#127 [ refact ] : #126 popular post refact
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/popularpost/controller/PopularPostController.java
  backend/src/main/java/com/example/booktree/popularpost/service/PopularPostService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  frontend/src/app/blog/page.tsx
  frontend/src/app/follow/page.tsx
Labels: refact

#128 [ refact ] : #118 blog,follow refact
  frontend/src/app/blog/page.tsx
  frontend/src/app/follow/page.tsx
Labels: refact

#135 [ front ] : #97 블로그상세페이지, 마이페이지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/detail/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/mypage/page.tsx
Labels: front

#142 [ feature ] #141 : 전체페이지 사이즈 수정
  frontend/src/app/components/Header.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
Labels: feature

#150 Front/149 회원정보수정페이지
  frontend/src/app/account/edit/edit.module.css
  frontend/src/app/account/edit/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/app/register/register.module.css
  frontend/src/app/withdrawal/page.tsx
  frontend/src/app/withdrawal/withdrawal.module.css
Labels: front

#152 [ fix ] : 테스트 하면서 나왔던 문제들 해결 ( 응답 형식 등
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/jwt/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/example/booktree/user/controller/UserController.java
  backend/src/main/java/com/example/booktree/user/service/UserService.java
Labels: test

#155 [fix] : #154 : 이미지 첨부 안하면 오류나는 이슈 해결
  backend/src/main/java/com/example/booktree/post/dto/request/PostRequestDto.java
Labels: refact

#157 [ fix ] : #156 셀프 팔로우 예외처리
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/follow/service/FollowService.java
Labels: refact

#205 [ fix ] :#174 : 조회수 오류 수정
  frontend/next.config.js
Labels: refact

#204 Fix/#174 게시글 인기순 정렬 수정
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/popularpost/controller/PopularPostController.java
  backend/src/main/java/com/example/booktree/popularpost/service/PopularPostService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  backend/src/main/java/com/example/booktree/user/dto/response/UserProfileResponseDto.java
  frontend/src/app/account/edit/edit.module.css
  frontend/src/app/account/edit/page.tsx
  frontend/src/app/account/editPassword/page.tsx
  frontend/src/app/account/findAccount/findId/page.tsx
  frontend/src/app/account/login/page.tsx
  frontend/src/app/blog/[postId]/detail/page.tsx
  frontend/src/app/page.tsx
  frontend/src/stores/auth/loginMember.tsx
Labels: feature, refact

#209 Front/feat/174 게시글 경로 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/blog/[id]/detail/page.tsx
  frontend/src/app/blog/post/[id]/list/page.tsx
  frontend/src/app/blog/post/page.tsx
  frontend/src/app/example/page.tsx
  frontend/src/app/post/[postId]/detail/get/page.tsx
Labels: refact

#207 [ front / feat ] : #206 category crud connect
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/test/java/com/example/booktree/popularpost/service/PopularPostServiceTest.java
  frontend/.idea/.gitignore
  frontend/.idea/frontend.iml
  frontend/.idea/misc.xml
  frontend/.idea/modules.xml
  frontend/.idea/vcs.xml
  frontend/src/app/account/findAccount/findPassword/page.tsx
  frontend/src/app/blog/post/[Id]/detail/page.tsx
  frontend/src/app/category/page.tsx
  frontend/src/app/components/CategoryBox.tsx
  frontend/src/app/components/CategoryGrid.tsx
  frontend/src/app/main/category/[slug]/page.tsx
  frontend/src/app/mypage/[id]/page.tsx
  frontend/src/app/page.tsx
  frontend/tsconfig.json
Labels: feature, front, backend

#208 [ front / feat ] #200 : 게시물검색 기능
  backend/src/main/java/com/example/booktree/config/SecurityConfigBookTree.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  frontend/src/app/blog/[id]/page.tsx
  frontend/src/app/components/Header.tsx
  frontend/src/app/search/page.tsx
Labels: feature, front

#219 [ front / feat ] : #217 카테고리를 보여줘야 하는 페이지 연동
  backend/src/main/java/com/example/booktree/blog/controller/BlogController.java
  backend/src/main/java/com/example/booktree/blog/repository/BlogRepository.java
  backend/src/main/java/com/example/booktree/blog/service/BlogService.java
  backend/src/main/java/com/example/booktree/category/controller/CategoryController.java
  backend/src/main/java/com/example/booktree/category/dto/response/AllCategoryResponseDto.java
  backend/src/main/java/com/example/booktree/category/service/CategoryService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  frontend/src/app/blog/[id]/page.tsx
  frontend/src/app/components/CategoryGrid.tsx
  frontend/src/app/main/category/[slug]/page.tsx
  frontend/src/app/mypage/editCategory/[userId]/page.tsx
  frontend/src/app/post/[postId]/detail/get/page.tsx
  frontend/src/app/post/write/page.tsx
Labels: feature, front, backend

#224 [ Front/feat ] :#174 게시글
  frontend/src/app/post/write/page.tsx
Labels: feature, front

#228 [ Front/feat ] : #174 게시글 작성 기능
  frontend/src/app/post/write/page.tsx
Labels: feature, front

#235 [ front / feat ] #234 : 검색게시글 클릭 시 게시글이동
  frontend/src/app/search/page.tsx
Labels: feature, front

#247 [ front/feat ] #197 : 게시글 detail 댓글 crud
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  frontend/src/app/account/login/page.tsx
  frontend/src/app/components/CommentForm.jsx
  frontend/src/app/post/[postId]/detail/get/page.tsx
Labels: feature, front

#253 Front/feat/174 게시글
  frontend/src/app/blog/post/[id]/list/page.tsx
  frontend/src/app/post/[postId]/detail/get/page.tsx
  frontend/src/app/post/write/page.tsx
Labels: feature, refact, front

#266 Front/feat/#174 게시글입력
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/popularpost/controller/PopularPostController.java
  backend/src/main/java/com/example/booktree/popularpost/service/PopularPostService.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/response/PostDetailResponseDto.java
  backend/src/main/java/com/example/booktree/post/entity/Post.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: refact

#281 [ Front/feat ] #174 게시글, 게시글 좋아요
  frontend/src/app/post/[postId]/detail/get/page.tsx
Labels: feature, front

#286 [ front/feat ] #248 : 게시글대댓글
  backend/src/main/java/com/example/booktree/comment/dto/CommentDto.java
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/reply/dto/ReplyDto.java
  backend/src/main/java/com/example/booktree/reply/service/ReplyService.java
  frontend/src/app/components/CommentsSection.tsx
  frontend/src/app/post/[postId]/detail/get/page.tsx
Labels: feature, front

#302 [ front / feat ] #295 : 댓글좋아요
  backend/src/main/java/com/example/booktree/like_comment/service/LikeCommentService.java
  backend/src/main/java/com/example/booktree/like_reply/service/LikeReplyService.java
  frontend/src/app/components/CommentsSection.tsx
Labels: feature, front

#334 [ front/feat ] #303 : 댓글좋아요
  backend/src/main/java/com/example/booktree/comment/controller/CommentController.java
  backend/src/main/java/com/example/booktree/comment/dto/CommentDto.java
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/like_reply/controller/LikeReplyController.java
  backend/src/main/java/com/example/booktree/like_reply/dto/LikeReplyDto.java
  backend/src/main/java/com/example/booktree/like_reply/repository/LikeReplyRepository.java
  backend/src/main/java/com/example/booktree/like_reply/service/LikeReplyService.java
  backend/src/main/java/com/example/booktree/reply/dto/ReplyDto.java
  backend/src/main/java/com/example/booktree/reply/entity/Reply.java
  backend/src/main/java/com/example/booktree/reply/service/ReplyService.java
  frontend/src/app/components/CommentsSection.tsx
Labels: feature, front

#353 [ fix ] : #347 프론트 쪽 블로그 페이지 상단에 유저닉네임 안뜨는 이슈 해결
  backend/src/main/java/com/example/booktree/blog/controller/BlogController.java
  backend/src/main/java/com/example/booktree/blog/dto/response/BlogResponseDto.java
  backend/src/main/java/com/example/booktree/blog/service/BlogService.java
Labels: backend, fix

#358 [ front/feat ] #350 : 댓글버튼숨기기
  backend/src/main/java/com/example/booktree/comment/service/CommentService.java
  backend/src/main/java/com/example/booktree/reply/dto/ReplyDto.java
  backend/src/main/java/com/example/booktree/reply/service/ReplyService.java
  frontend/src/app/components/CommentsSection.tsx
Labels: feature, front

#359 [ fix ] : /#347 게시글 생성 성공 시 해당 게시글로 리다이렉트 되기 위한 Post 관련 로직 추가
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: backend, fix

#360 [ Front/feat ] #174 게시글 생성 성공 시 해당 게시글로 리다이렉트, 게시글 실패 시 해당 블로그로 리다이렉트
  frontend/src/app/post/[postId]/detail/get/page.tsx
  frontend/src/app/post/write/page.tsx
Labels: front, fix

#365 [ front / fix ] #363 : 댓글UI색상변경
  frontend/src/app/components/CommentsSection.tsx
Labels: front, fix

#367 [ front / fix ] #364 : 검색UI 페이지버튼 수정
  frontend/src/app/search/page.tsx
Labels: front, fix

#391 Feat/#347 게시글 생성 시 내용 글 사이에 이미지 위치할 수 있도록 백엔드 로직 추가
  backend/src/main/java/com/example/booktree/exception/ExceptionCode.java
  backend/src/main/java/com/example/booktree/image/controller/ImageController.java
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/dto/request/PostRequestDto.java
  backend/src/main/java/com/example/booktree/post/entity/Post.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  backend/src/main/resources/application.yml
Labels: backend, fix

#401 [ Fix/#389 ] 게시글 수정 내용 사이 이미지
  frontend/src/app/post/[postId]/detail/get/page.tsx
Labels: refact, front

#406 [fix ] #403 : 좋아요게시글삭제
  backend/src/main/java/com/example/booktree/likepost/repository/LikePostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
Labels: fix

#416 [ front/fix ]#389 게시글 생성, 수정 시 Content에 텍스트 용량 넉넉하게, Content 이미지 여러개를 텍스트 사이사이 첨부 가능하게
  frontend/src/app/post/[postId]/detail/get/page.tsx
  frontend/src/app/post/write/page.tsx
Labels: front, fix

#418 [ fix ] #389 게시글 생성, 수정 시 Content에 용량 넉넉하게, Content 이미지 여러개를 텍스트 사이사이 첨부 가능하게 백엔드 수정
  backend/src/main/java/com/example/booktree/post/controller/PostController.java
  backend/src/main/java/com/example/booktree/post/entity/Post.java
  backend/src/main/java/com/example/booktree/post/repository/PostRepository.java
  backend/src/main/java/com/example/booktree/post/service/PostService.java
  backend/src/main/resources/application.yml
Labels: backend, fix
